Output pointers using printf format "%p" instead of "0x%lx". Fixes the following:
libmc1322x/lib/maca.c: In function 'Print_Packets':
libmc1322x/lib/maca.c:196: error: format '%lx' expects type 'long unsigned int', but argument 2 has type 'unsigned int'
libmc1322x/lib/maca.c:199: error: format '%lx' expects type 'long unsigned int', but argument 2 has type 'unsigned int'
libmc1322x/lib/maca.c:204: error: format '%lx' expects type 'long unsigned int', but argument 2 has type 'unsigned int'
libmc1322x/lib/maca.c:207: error: format '%lx' expects type 'long unsigned int', but argument 2 has type 'unsigned int'
libmc1322x/lib/maca.c:212: error: format '%lx' expects type 'long unsigned int', but argument 2 has type 'unsigned int'
libmc1322x/lib/maca.c:215: error: format '%lx' expects type 'long unsigned int', but argument 2 has type 'unsigned int'
libmc1322x/lib/maca.c:219: error: format '%lx' expects type 'long unsigned int', but argument 2 has type 'unsigned int'
libmc1322x/lib/maca.c:220: error: format '%lx' expects type 'long unsigned int', but argument 2 has type 'unsigned int'
libmc1322x/Makefile.include:99: recipe for target 'libmc1322x/lib/maca.o' failed